### ISSUE TITLE
Meeting 29. Mai 2019

### ISSUE THREAD

**Issue by Hanswurstig** [JonasOelke/xbase#15]
**To Do bis Sonntag Abend**

- [x] Login/Registrierung @MalinBoeckmann 
- kleine Schrift größer (Hover und ?)
- Pfeil rechts weiter rechts
- Passwortkasten länger
- Slider auf Login
- Passwort (8 Zeichen und so prüfen) @JonasOelke 
- auf HAW-Mail prüfen @JonasOelke 

- [x]  Startseite @Viktyny 
- Aufgabe hinzufügen Button weg
- Oranger Kasten kleiner als Aufgabensammlung

- [x] Layout allgemein (Header/Footer) @Viktyny 
- Navigation Startseite und Aufgabensammlung Schrift größer

- [x] Aufgabensammlung @MalinBoeckmann 
- Pfeil in Auswahlmenü hinzufügen
- Abstand zwischen Auswahlmenü "Media Systems" und "Mathe 2" evtl. kleiner
- Auswahlbutton an Kasten ausrichten
- scrollen checken mit mehreren Aufgaben und Footer Hintergrund checken

- [x] Aufgabe @Hanswurstig 
- Placeholder Lösung- und Kommentarfeld
- Kästen größer (Lösung/Kommentar)
- Lösung/Kommentar Style
- Ausklappbar "Alle Lösungen anzeigen" @Viktyny 
- Datumsformat deutsch Bsp.: TT.MM.JJJJ @JonasOelke 
- Layout allgemein (Button runter, Text einrücken, Leerzeichen...)
- Lösung: warum 2 Buttons? ("eine Lösung hinzufügen" und "Lösung einreichen")
- alles in orangen Kasten probieren
- bei Hover Mauszeiger ändern bei Klappdingern 
- Bei Lösungen/Kommentaren: Linien in Tabelle unterhalb einfügen

- [x] Aufgabe hinzufügen @Viktyny 
- Überschrift innerhalb Kasten
- Kasten breiter (wie Box)
- Lösungskasten auch größer
- Lösung Text raus

**Comment by JonasOelke** [comment]
Alle Aufgaben sind erledigt.
