### ISSUE TITLE
Meeting 05.06.2019

### ISSUE THREAD

**Issue by MalinBoeckmann** [JonasOelke/xbase#17]
Bericht APRG:

Bis Freitag Stundenzettel vervollständigen.
Alle Dokumente in Git hochladen und Plaß bis 11.06 zuschicken inkl. Hinweis, dass alle Dokumente in Git sind. @JonasOelke 

- [x] Stundenzettel @Hanswurstig 

- [x] Fließdiagramm zur Struktur @Hanswurstig 

- [x] 1 Seite Bericht: Zeile und Ergebnisse @Viktyny 

- [x] Git-Repository aufräumen @JonasOelke 

Bericht Projektmanagement:

Bis 14.06.2019 fertig.
Mittwoch, 12.06.2019 um 09:00 Treffen in Bib, um Text zusammen zu überarbeiten.

- [x] Zusammenfassung Inhalte Bericht aus Folien bis Samstagabend @Viktyny @MalinBoeckmann 

- [x] Jeder fasst stichpunktartig seine Gedanken zu einzelnen Punkten zusammen bis Sonntagabend

- [x] Bericht in Fließtext schreiben @MalinBoeckmann

**Comment by JonasOelke** [comment]
Alle Aufgaben sind erledigt.
